from typing import Protocol

from api.domain import Message
from api.models import User
from api.schemas import UserCreateSchema


class UserRepositoryPort(Protocol):
    def add(self, item: UserCreateSchema) -> User: ...

    def get(self, user_id: int) -> User: ...

    def list_users(self) -> list[User]: ...

    def get_by_username(self, username: str) -> User: ...

    def update(self, user_id: int, item: UserCreateSchema) -> User: ...

    def delete(self, user_id: int) -> None: ...


class UserUnitOfWorkPort(Protocol):
    users: UserRepositoryPort

    def __enter__(self) -> "UserUnitOfWorkPort": ...

    def __exit__(self, exc_type, exc_value, traceback) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...


class MessageRepositoryPort(Protocol):
    def get_by_tid(self, tid: int, limit: int = 100) -> list[Message]: ...

    def get_max_id(self, tid: int) -> int: ...

    def add_by_tid(self, tid: int, messages: list[str]) -> list[Message]: ...
